version: '3.8'

services:
  web.app:
    container_name: web.app
    build:
      context: ./web.app
      target: development
    env_file:
      - ./web.app/.env
    ports:
      - ${WEB_APP_PORT}:${WEB_APP_PORT}
    environment:
      - WEB_APP_PORT=${WEB_APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./web.app:/app
    command: npm run start:dev
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strawbrary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
    restart: always
  react.app:
    profiles: ["full"]
    container_name: react.app
    build:
      context: ./react.app
      target: development
    env_file:
      - ./react.app/.env
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - REACT_APP_WEBPACK_DEV_PORT=${REACT_APP_WEBPACK_DEV_PORT}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - ${REACT_APP_WEBPACK_DEV_PORT}:${REACT_APP_WEBPACK_DEV_PORT}
    volumes:
      - ./react.app:/app
    command: npm run start
    depends_on:
      - web.app
    tty: true
    stdin_open: true

