version: '3.8'

services:
  web.app:
    container_name: web.app
    build:
      context: ./web.app
      target: production
    env_file:
      - ./web.app/.env
    ports:
      - ${WEB_APP_PORT}:${WEB_APP_PORT}
    environment:
      - WEB_APP_PORT=${WEB_APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./web.app:/app
    command: npm run start:prod
    depends_on:
      - postgres
  #
  react.app:
    container_name: react.app
    build:
      context: ./react.app
      target: development
    env_file: ./react.app/.env
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    ports:
      - 3001:3001
    command: npm run start
    depends_on:
      - web.app
  #
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strawbrary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
    restart: always
  #
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_EXPOSED_PORT}:80
    volumes:
      - ./nginx/:/usr/local/etc/nginx
    command: [ "nginx", "-g", "daemon off;" ]
    depends_on:
      - react.app
      - web.app



