version: '3.8'

services:
  wab.app:
    container_name: wab.app
    build:
      context: ./web.app
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./web.app:/app
    command: npm run start:dev
    env_file: 
      - ./web.app/.env
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:qwerty@postgres:5432/strawbrary?schema=public
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strawbrary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
    restart: always
