import { LibraryItem } from '@prisma/client';

export const mock_library_items: LibraryItem[] = [
  {
    id: 1,
    title: 'meep',
    author: 'Izzy',
    pages: 4,
    runTimeMinutes: null,
    isBorrowable: true,
    borrower: null,
    borrowDate: null,
    type: 'Book',
    categoryId: 1,
  },
  {
    id: 2,
    title: 'meep',
    author: 'Izzy',
    pages: 4,
    runTimeMinutes: null,
    isBorrowable: true,
    borrower: null,
    borrowDate: null,
    type: 'Book',
    categoryId: 1,
  },
  {
    id: 3,
    title: 'meep',
    author: 'Izzy',
    pages: 4,
    runTimeMinutes: null,
    isBorrowable: true,
    borrower: null,
    borrowDate: null,
    type: 'Book',
    categoryId: 1,
  },
  {
    id: 4,
    title: 'meep',
    author: 'Izzy',
    pages: 4,
    runTimeMinutes: null,
    isBorrowable: true,
    borrower: null,
    borrowDate: null,
    type: 'Book',
    categoryId: 1,
  },
];
